#!/bin/sh

GUIDE=Guide.html

case $LANG in
	de*) GUIDE=de/Anleitung.html ;;
	it*) GUIDE=it/Guida.html ;;
esac

if [ -n "`which rox 2> /dev/null`" ]; then
	exec rox "`dirname $0`/$GUIDE"
fi

# Get it through Zero Install instead
exec 0run "rox.sourceforge.net/rox 2003-10-07" "`dirname $0`/$GUIDE"
