#!/usr/bin/env perl

chdir "../../ROX-Session";

system "cvs rel .";

open(VER, "./AppRun --version 2>&1 |") or die "open(): $!";
while (<VER>) {
  last if /^ROX-Session/;
}
close(VER);

/(\d+(\.\d+)*)$/;

$version = $1;
$_=$1;
s/\./_/g;
$dash = $_;

print "Check the manual is up-to-date!\n";
print "Version $version ($dash) --- OK?\n";

<STDIN> =~ /^[yY]/ or die "OK, fix the version number!\n";

system "cvs tag -F Release-$dash";
system "cd ROX-Session/src/po; ./update-po; ./dist";

chdir;

mkdir "ROX-Session-$version", 0775 or warn "mkdir() failed: $!\n";
chdir "ROX-Session-$version";

system "cvs -d:ext:tal197\@cvs.sourceforge.net:/cvsroot/rox export -r Release-$dash ROX-Session";
#system "cvs -d:pserver:anonymous\@cvs.rox.sourceforge.net:/cvsroot/rox export -r Release-$a-$b-$c ROX-Session";

system "cd ROX-Session/src; autoconf";
mkdir "ROX-Session/Messages";
system "cp ~/Projects/ROX-Session/Messages/*.gmo ROX-Session/Messages";

chdir "..";
system "tar czf ROX-Session-$version.tgz ROX-Session-$version";
system "rm -r ROX-Session-$version";

print "OK, done\n";
